export const PLACE_CREATE_REQUEST = "PLACE_CREATE_REQUEST";
export const PLACE_CREATE_FAIL = "PLACE_CREATE_FAIL";
export const PLACE_CREATE_SUCCESS = "PLACE_CREATE_SUCCESS";

export const PLACE_LIST_REQUEST = "PLACE_LIST_REQUEST";
export const PLACE_LIST_SUCCESS = "PLACE_LIST_SUCCESS";
export const PLACE_LIST_FAIL = "PLACE_LIST_FAIL";
export const PLACE_LIST_RESET = "PLACE_LIST_RESET";