export const BOOTHS_LIST_REQUEST = "BOOTHS_LIST_REQUEST";
export const BOOTHS_LIST_SUCCESS = "BOOTHS_LIST_SUCCESS";
export const BOOTHS_LIST_FAIL = "BOOTHS_LIST_FAIL";
export const BOOTHS_LIST_RESET = "BOOTHS_LIST_RESET";



export const BOOTHS_CREATE_REQUEST = "BOOTHS_CREATE_REQUEST";
export const BOOTHS_CREATE_FAIL = "BOOTHS_CREATE_FAIL";
export const BOOTHS_CREATE_SUCCESS = "BOOTHS_CREATE_SUCCESS";