export const VOTER_LIST_REQUEST = "VOTER_LIST_REQUEST";
export const VOTER_LIST_SUCCESS = "VOTER_LIST_SUCCESS";
export const VOTER_LIST_FAIL = "VOTER_LIST_FAIL";
export const VOTER_LIST_RESET = "VOTER_LIST_RESET";

