export { default as SignIn } from './SignUp'
export { default as SignUp } from './SignupSimple'
export { default as adminSignIn } from './adminLogin'
export {default as dashboard} from './dashboard.js'
export { default as Kaadders } from './assignedPlace'
export { default as booth } from './booth'
export { default as addPlace } from './addPlace'
export { default as assignedPlace } from './userPlaceAssigne.js'
export { default as boothVooter } from './boothVoter'